language: node_js
node_js:
- '0.10'
install:
- npm install
- npm install -g gulp
before_deploy:
- gulp build --tag=${TRAVIS_BRANCH}
deploy:
  provider: s3
  access_key_id: AKIAII7TI4JOMGRAWTNA
  bucket: cc.silktide.com
  local-dir: build
  skip_cleanup: true
  on:
    tags: true
  secret_access_key:
    secure: IDrZeF+MWoTQsPI+PoSpVK6FACIW4o6lUOwsQ2D84ardTMYyvVHnsiFcHugj1Ey07Tw99yR0rY+TKXs6FbnCRZr0ZqKNru2NsXsOHj8fwWGGMzdbtpSkct9Is88LHNNoIZBgi5C+zRbHYgk+F7ZqM8AQUGARgdIWkO3kbM/0aiw=
