# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('template_name', models.CharField(max_length=200)),
                ('slug', models.CharField(default='', max_length=200)),
                ('parent', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('label', 'language', 'key')]),
        ),
    ]
