# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='template_name',
            new_name='template',
        ),
    ]
