# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contento', '0002_auto_20160808_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
