# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contento', '0004_auto_20160808_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='slug',
            new_name='url',
        ),
    ]
