# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 17:49
from __future__ import unicode_literals

import contento.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contento', '0008_page_fullpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='key',
            field=contento.fields.NullCharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='language',
            field=contento.fields.NullCharField(blank=True, max_length=200, null=True),
        ),
    ]
